spring:
  application:
    name: microservice-discovery-eureka-high-availability
---
server:
  port: 8761
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://af:123456@localhost:8762/eureka/
security:
  user:
    name: af
    password: 123456
---
server:
  port: 8762
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://af:123456@localhost:8761/eureka/
security:
  user:
    name: af
    password: 123456