server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://af:123456@localhost:8761/eureka/
security:
  user:
    name: af
    password: 123456